import React from 'react'
import { Link } from 'react-router-dom'

const SampleReportPage = () => {
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })

  return (
    <div className="sample-report-page">
      {/* Lightweight Header */}
      <div className="container" style={{ paddingTop: 20, paddingBottom: 10 }}>
        <Link to="/dashboard" className="btn btn-secondary">← Back to Your Dashboard</Link>
      </div>

      {/* Report Cover Page */}
      <section className="report-cover">
        <div className="report-container">
          <h1 className="report-main-title">Supply Chain Intelligence Analysis: Sample Report</h1>
          <p className="report-subtitle">Tailored for Overseas Energy Storage Integrators</p>
          
          <hr className="report-divider" />
          
          <div className="project-details">
            <p><strong>Project Type:</strong> Commercial & Industrial (C&I) Energy Storage System (100kW/232kWh)</p>
            <p><strong>Target Market:</strong> Germany</p>
            <p><strong>Report Date:</strong> {currentDate}</p>
            <p><strong>Confidentiality Level:</strong> Public Sample</p>
          </div>
        </div>
      </section>

      {/* Letter to Client */}
      <section className="report-letter">
        <div className="report-container">
          <h2>Letter to the Prospective Client</h2>
          <blockquote className="client-letter">
            <p>To the Decision-Maker,</p>
            <p>When faced with a sea of supplier information, the real challenge is never about finding a list, but about answering three core questions:</p>
            <ul>
              <li>Who is the right partner for my specific project?</li>
              <li>How do I mitigate the delivery and quality risks hidden behind glossy brochures?</li>
              <li>What is the optimal procurement strategy for my situation?</li>
            </ul>
            <p>This report, generated by the SupplyFinder.ai AI Engine, is designed to show you how we transform the complex global sourcing process from weeks of manual screening into a clear, trustworthy, and actionable decision-support brief.</p>
            <p><strong>This is not just a list. This is a strategic briefing.</strong></p>
          </blockquote>
        </div>
      </section>

      {/* Executive Summary */}
      <section className="report-summary">
        <div className="report-container">
          <h2>1. Executive Summary & Core Findings</h2>
          <p>Based on your simulated need for a [C&I ESS] targeting the [German] market, our AI system scanned and evaluated data from over 600 active suppliers in our pre-vetted global database. This analysis, which would take a human team weeks, was completed in under 15 minutes, identifying 3 top-potential candidates for you.</p>
          
          <div className="core-conclusions">
            <h3>Core Conclusions:</h3>
            <ul>
              <li className="primary-recommendation">
                <span className="recommendation-badge">RECOMMENDED</span>
                <strong>Primary Recommendation: Supplier B</strong> - Most comprehensive certifications, lowest risk profile, the safest choice for ensuring smooth grid connection.
              </li>
              <li><strong>Cost-First Alternative: Supplier A</strong> - Most competitive on price, but requires active <strong>delivery risk management</strong>.</li>
              <li><strong>Technical Alternative: Supplier C</strong> - Outstanding customization capabilities, ideal for projects with unique technical requirements.</li>
            </ul>
          </div>

          <div className="risk-alert">
            <h3>Critical Risk Alert:</h3>
            <p>Our system monitors show that the <strong>lead times for battery systems fully certified for the German VDE-AR-N 4110 medium-voltage grid connection standard have extended by an average of 2-3 weeks compared to last month</strong>. We recommend building a buffer into your project timeline.</p>
          </div>
        </div>
      </section>

      {/* Supplier Comparison Table */}
      <section className="supplier-comparison">
        <div className="report-container">
          <h2>2. In-Depth Supplier Comparison Analysis</h2>
          <div className="comparison-table-wrapper">
            <table className="comparison-table">
              <thead>
                <tr>
                  <th>Dimension</th>
                  <th>Supplier A (Cost Leader)</th>
                  <th className="recommended">Supplier B (Quality & Compliance Benchmark)</th>
                  <th>Supplier C (Technology Specialist)</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><strong>Core Strength</strong></td>
                  <td>Economies of scale, strong cost control</td>
                  <td className="recommended">Complete certification portfolio, strong brand reputation, financial transparency</td>
                  <td>Software-defined storage, deeply customizable BMS support</td>
                </tr>
                <tr>
                  <td><strong>Target Markets</strong></td>
                  <td>Europe, Africa, Southeast Asia</td>
                  <td className="recommended"><strong>North America, Germany, Australia, Japan</strong></td>
                  <td>Global (focus on high-end custom projects)</td>
                </tr>
                <tr>
                  <td><strong>Key Certifications</strong></td>
                  <td>CE, IEC 62619</td>
                  <td className="recommended"><strong>UL 9540, VDE-AR-N 4110, IEC 62477-1</strong></td>
                  <td>CE, IEC 62619, UN38.3</td>
                </tr>
                <tr>
                  <td><strong>AI Risk Assessment</strong></td>
                  <td><strong>Delivery Risk:</strong> Tight capacity, confirmed orders require capacity locking.<br/><strong>Suggestion:</strong> Tie payments to delivery milestones.</td>
                  <td className="recommended"><strong>Low Risk:</strong> Publicly listed, diversified supply chain, stable quality.</td>
                  <td><strong>Tech Risk:</strong> Overly complex customization may impact timeline.<br/><strong>Suggestion:</strong> Define scope clearly, use phased acceptance.</td>
                </tr>
                <tr>
                  <td><strong>Procurement Suggestion</strong></td>
                  <td>Suitable for cost-sensitive projects that can tolerate delivery fluctuations.</td>
                  <td className="recommended"><strong>Highly recommended as a primary supplier</strong>, especially for projects with stringent certification and reliability demands.</td>
                  <td>Recommended for pioneering tech validation or when standard products don't meet needs.</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* Insights Section */}
      <section className="report-insights">
        <div className="report-container">
          <h2>3. Insights Beyond the Table</h2>
          
          <div className="opportunity-analysis">
            <h3>🔍 Potential Opportunity Analysis</h3>
            <ul>
              <li><strong>Negotiation Leverage:</strong> <strong>Supplier A</strong> is seeking "lighthouse customers" for its new production line. You may secure an extra <strong>5-10%</strong> discount on initial orders.</li>
              <li><strong>Hidden Value:</strong> <strong>Supplier B's</strong> local technical team in Germany can provide <strong>on-site grid connection support</strong>, saving significant engineer travel costs and time.</li>
              <li><strong>Future-Proofing:</strong> <strong>Supplier C's</strong> modular design allows for easier future <strong>capacity expansion and technology upgrades</strong>, enhancing long-term investment value.</li>
            </ul>
          </div>

          <div className="risk-mitigation">
            <h3>⚠️ Risk Alert & Mitigation</h3>
            <p><strong>Identified Risk:</strong> Our data models flag that <strong>Supplier A's</strong> primary battery cell supplier is involved in a procurement contract dispute, potentially affecting cell supply in the next 3-6 months.</p>
            <p><strong>Mitigation Strategy:</strong></p>
            <ol>
              <li>Include strict supply chain disruption clauses in the contract.</li>
              <li>Use <strong>Supplier B</strong> as a backup to increase negotiation pressure.</li>
            </ol>
          </div>
        </div>
      </section>

      {/* Call to Action */}
      <section className="optimized-cta">
        <div className="cta-container">
          <h2 className="cta-main-title">This is a demo report inside the platform</h2>
          
          <p className="cta-description">
            The content above demonstrates our analysis format and the type of insights you can expect. To generate a <strong>project-specific</strong> report, start a real project with your requirements.
          </p>
          
          <div className="final-cta">
            <Link className="btn btn-primary" to="/">Submit your real requirements</Link>
            <Link className="btn btn-secondary" to="/dashboard">Back to Dashboard</Link>
          </div>
        </div>
      </section>
    </div>
  )
}

export default SampleReportPage
